#!/bin/bash -x
#
# This script builds the Varnish Cache release RPM.
#
# Author: Lasse Karstensen <lkarsten@varnish-software.com>, September 2015.
#
set -o errexit

if [ -z "${ELVER}" ]; then
	echo "ERROR: Please set environment variable ELVER. (el6|el7)"
	exit 1;
fi

rm -rf rpm-build
mkdir -p rpm-build

mock --init --quiet
mock --buildsrpm -D "dist .${ELVER}" --spec *.spec --source content/  --resultdir rpm-build/varnish-${ELVER}
mock --clean --quiet
mock -D "dist .${ELVER}" --resultdir rpm-build/varnish-${ELVER} --rebuild rpm-build/varnish-*/varnish*src*rpm
