#!/bin/bash -x
#
# This script builds the Varnish Cache release RPM.
#
# Author: Lasse Karstensen <lkarsten@varnish-software.com>, September 2015.
#
set -o errexit

rm -rf build
mkdir -p build

mock --init --quiet
mock  --buildsrpm --spec *.spec --source content/  --resultdir build
mock --clean --quiet
mock --resultdir build  --rebuild build/varnish*src*rpm
